# Generated by Django 2.2.6 on 2019-11-03 12:15

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191103_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=django_multitenant.fields.TenantForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
