# Generated by Django 2.2.6 on 2019-11-03 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_multitenant.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('all_day', models.BooleanField(default=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_datetime_utc', models.DateTimeField(null=True)),
                ('appointment_duration', models.DurationField()),
                ('appointment_reason', models.CharField(max_length=1000)),
                ('appointment_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('show', 'Show'), ('no_show', 'No Show'), ('canceled', 'Canceled'), ('late_canceled', 'Late Canceled')], default='scheduled', max_length=50)),
                ('created_by', models.CharField(max_length=50)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_by', models.CharField(max_length=50)),
                ('colour', models.CharField(default='#96b3e6', max_length=20)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
